### ISSUE TITLE
Subscription selection before deploy

### ISSUE THREAD

**Issue by JWStarkie** [tayganr/purviewdemo#16]
**Current state**
- resource group and resources deployed to the default AzureContext

**Limitations**
- could lead to deployment in the wrong subscription

**Request**
We could either 
1. have some selection process as part of deploy or
2. some prerequisites included in README to ensure user has correct subscription selected

**Comment by tayganr** [comment]
Since the solution has transitioned to using the deploy to Azure button method, users can now select their own Subscription and Resource Group as part of the deployment process.
