### ISSUE TITLE
Authentication Token Expired

### ISSUE THREAD

**Issue by Kartik1899** [tayganr/purviewdemo#18]
Deployment is taking 30+ minutes and the access token expires before the deployment is completed.
![error](https://user-images.githubusercontent.com/52946414/142039073-877be6a8-ce46-4f4f-a1fd-2d19b5e33e5d.png)

**Comment by tayganr** [comment]
Thanks @Kartik1899 . This issue should now be resolved. There were some breaking changes with the New-AzADServicePrincipal cmdlet due to the migration from Azure AD Graph to Microsoft Graph. The script has been updated to cater for these changes.
