### ISSUE TITLE
Get it working as is

### ISSUE THREAD

**Issue by JWStarkie** [tayganr/purviewdemo#21]

**Comment by JWStarkie** [comment]
I haven't had chance to test this yet. Just wanted to check if we can mark this as done? Is it all working as expected? @tayganr

**Comment by tayganr** [comment]
Updates published to cater for breaking changes introduced by [Azure AD to Microsoft Graph migration in Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/azps-msgraph-migration-changes?view=azps-7.3.2).
