### ISSUE TITLE
Test connection w/ Lineage extraction (preview) fails

### ISSUE THREAD

**Issue by isdataninja** [tayganr/purviewdemo#23]
Test connection w/ Lineage extraction (preview) fails

![image](https://user-images.githubusercontent.com/98440618/162868481-981a1ace-f756-43f0-a36f-e5ecb2ea1c8e.png)

This is due to the newly introduced Lineage extraction (preview). For now, manually provide the db_owner role in Azure SQL Database for your Azure Purview MSI, and create the master key while we add this as an enhancement. 

+ @isantillan1 @tayganr @leaubl

**Comment by leaubl** [comment]
@isdataninja 
Please provide the step by step instructions with screenshots for "manually provide the db_owner role in Azure SQL Database for your Azure Purview MSI, and create the master key".
Thanks.

**Comment by isdataninja** [comment]
> @isdataninja 
> Please provide the step by step instructions with screenshots for "manually provide the db_owner role in Azure SQL Database for your Azure Purview MSI, and create the master key".
> Thanks.

https://docs.microsoft.com/en-us/azure/purview/register-scan-azure-sql-database#lineagepreview


Create user <purview-account> FROM EXTERNAL PROVIDER
GO
EXEC sp_addrolemember 'db_owner', <purview-account> 
GO

Create master key
Go

**Comment by isdataninja** [comment]
Instructions updated to include:

> "Lineage extraction (preview)" is off
