### ISSUE TITLE
Template deployment expects more permissions (Owner) 

### ISSUE THREAD

**Issue by petender** [tayganr/purviewdemo#30]
Tried to deploy this template using Azure DevOps with the Service Connection/Service Principal having Contributor Permissions on Subscription level. However, this fails with not having authorized permissions. Can you confirm the deployment requires Owner permissions?

**Comment by MindedFree** [comment]
Hi @petender, It needs at least Owner-Permissions on Ressource-Group-Level as the script set some IAM-Settings (Contributor is not sufficient for these steps).

**Comment by petender** [comment]
Thanks for confirming! You might consider adding that in the 'Azure Subscription' bullet point, since not all who want to try this deployment might have Owner permissions on the subscription or Resource Group.
