### ISSUE TITLE
ResourceGroup Parameter (optional)

### ISSUE THREAD

**Issue by JWStarkie** [tayganr/purviewdemo#6]
**Current State**

- The scripts currently do not accomodate for use with an existing resource group.

**Limitation**

- The template, by default, deploys a new resource group for all resources. 

**Request**

- Expose an optional -ResourceGroup parameter for the preDeploymentScript.ps1.
- Add logic within the preDeploymentScript to check if a new resource group is required. 
- Include logic to cater for scenarios where the user provides no -ResourceGroup parameter.

**Comment by tayganr** [comment]
Since transitioning to the deploy to Azure button method, users have the option of deploying to either an existing or new resource group.
